# Generated by Django 4.2.13 on 2024-06-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_date_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='value',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.registratoin'),
        ),
        migrations.AlterField(
            model_name='registratoin',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
